project_id = "sovyrqzpavkuuycnfyac"

[functions.tradingview-webhook]
verify_jwt = false

[functions.send-calendar-reminder]
verify_jwt = false

[functions.economic-calendar]
verify_jwt = false

[functions.news-aggregator]
verify_jwt = false
